// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecurePay.Transactions.Api.Persistence;

#nullable disable

namespace SecurePay.Transactions.Api.Persistence.Migrations
{
    [DbContext(typeof(TransactionsDbContext))]
    [Migration("20260910211602_AddTransactionDestination")]
    partial class AddTransactionDestination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("WalletId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_wallet_id")
                        .HasFilter("wallet_id IS NOT NULL");

                    b.HasIndex("AccountType", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_platform_type_currency")
                        .HasFilter("wallet_id IS NULL");

                    b.ToTable("ledger_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_type_link", "(account_type = 'CustomerWallet' AND wallet_id IS NOT NULL)\r\nOR\r\n(account_type = 'PlatformClearing' AND wallet_id IS NULL)");
                        });
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid>("LedgerPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_posting_id");

                    b.HasKey("Id");

                    b.HasIndex("LedgerAccountId")
                        .HasDatabaseName("ix_ledger_entries_account_id");

                    b.HasIndex("LedgerPostingId", "LedgerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_entries_posting_account");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_ledger_entries_direction", "direction IN ('Debit', 'Credit')");
                        });
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.LedgerPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_postings_payment_transaction_id");

                    b.ToTable("ledger_postings", (string)null);
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_user_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_transactions_reference");

                    b.HasIndex("DestinationUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_payment_transactions_destination_user_id_created_at_utc")
                        .HasFilter("destination_user_id IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_payment_transactions_user_id_created_at_utc");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_transactions_user_id_idempotency_key");

                    b.ToTable("payment_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_transactions_destination", "(\r\n    transaction_type = 'Transfer'\r\n    AND destination_user_id IS NOT NULL\r\n    AND destination_user_id <> user_id\r\n)\r\nOR\r\n(\r\n    transaction_type IN ('Deposit', 'Withdrawal')\r\n    AND destination_user_id IS NULL\r\n)");
                        });
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.WalletAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_wallet_accounts_user_id_currency");

                    b.ToTable("wallet_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallet_accounts_balance_non_negative", "balance >= 0");
                        });
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.LedgerAccount", b =>
                {
                    b.HasOne("SecurePay.Transactions.Api.Domain.Entities.WalletAccount", null)
                        .WithOne()
                        .HasForeignKey("SecurePay.Transactions.Api.Domain.Entities.LedgerAccount", "WalletId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("SecurePay.Transactions.Api.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecurePay.Transactions.Api.Domain.Entities.LedgerPosting", null)
                        .WithMany("Entries")
                        .HasForeignKey("LedgerPostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.LedgerPosting", b =>
                {
                    b.HasOne("SecurePay.Transactions.Api.Domain.Entities.PaymentTransaction", null)
                        .WithOne()
                        .HasForeignKey("SecurePay.Transactions.Api.Domain.Entities.LedgerPosting", "PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SecurePay.Transactions.Api.Domain.Entities.LedgerPosting", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
